spring:
  application:
    name: KingAdmin
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

management:
  security:
    enabled: false #关掉安全认证
  context-path: /management #actuator的访问路径　


druid:
  pool:
    initialSize: 5  
    minIdle: 5  
    maxActive: 20  
    maxWait: 60000  
    timeBetweenEvictionRunsMillis: 60000  
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT 1 FROM DUAL  
    testWhileIdle: true  
    testOnBorrow: false  
    testOnReturn: false  
    poolPreparedStatements: true  
    maxPoolPreparedStatementPerConnectionSize: 20  
    filters: stat,wall,log4j  
    connectionProperties:
    druid.stat.mergeSql: true
    druid.stat.slowSqlMillis: 5000


#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.oukingtim.domain
  global-config:
    id-type: 3
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

fileUploadPath:
filePaht:

#
#swagger:
#   enabled: true
#   title: oms-API
#   description: API文档
#   base-package:  com.oukingtim.web
#   base-path: /**
#   exclude-path: /error
#   version: @project.version@